os: Windows Server 2012

environment:
  matrix:
    - CLI_VERSION: 1.0.0-preview2-003131

install:
  # Download install script to install .NET cli in .dotnet dir
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1 -Channel "preview" -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
  # show current dotnet info
  - ps: echo "Using dotnet '$((Get-Command dotnet).Path)'"
  - ps: dotnet --info

build_script:
  - ps: .\scripts\create_packages.ps1
  - ps: .\scripts\run_tests_tool.ps1
  - ps: .\scripts\run_tests_task.ps1

artifacts:
  - path: 'bin\packages\*.nupkg'

test: off 
version: 0.0.1.{build}
